# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!
target 'MQTT Chat' do
pod 'MQTTKit', :git => 'https://github.com/mobile-web-messaging/MQTTKit.git'
pod 'JSQMessagesViewController'
end

target 'MQTT ChatTests' do

end

target 'MQTT ChatUITests' do

end

